<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>menuTagihan</name>
   <tag></tag>
   <elementGuidId>bdf47e1f-3de4-4160-b380-3528a2839aab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;wrapper&quot;]/nav/div/div/ul/li[6]/ul/li[3]/ul/li[3]/a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
