<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ddlTermPembayaran</name>
   <tag></tag>
   <elementGuidId>cebe9613-50f1-4fa3-a51a-1a149e6ce3df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;page-wrapper&quot;]/div[3]/div/div/div[2]/div/div/div/div[1]/div[1]/div[2]/div[1]/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
