<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnHapusItemKonsinyasi1</name>
   <tag></tag>
   <elementGuidId>2f3bfe19-6742-413f-8265-7762e9b333ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;page-wrapper&quot;]/div[3]/div/div[3]/div/div/div[3]/div[3]/div[2]/button[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
