<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtDescription</name>
   <tag></tag>
   <elementGuidId>5d1a893b-e7d0-4f2c-a5b4-dfdbb7a0a150</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;page-wrapper&quot;]/div[3]/div/div[3]/div[2]/div[1]/div[2]/div/div[2]/div/div/div/div/div[2]/div/div/div</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;page-wrapper&quot;]/div[3]/div/div[3]/div[2]/div[1]/div[2]/div/div[2]/div/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;page-wrapper&quot;]/div[3]/div/div[3]/div[2]/div[1]/div[2]/div/div[2]/div/div/div/div</value>
   </webElementProperties>
</WebElementEntity>
