<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnScan</name>
   <tag></tag>
   <elementGuidId>d13b0c6c-2bcf-4571-9fa3-477e76d7398d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;page-wrapper&quot;]/div[3]/div/div/div/div/div[1]/div[1]/div/div[1]/div[5]/div/div/div/span/button</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
