<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtNoRefPemasok</name>
   <tag></tag>
   <elementGuidId>3f5ad1ac-eae1-40bf-920d-81e5d9b1cb60</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;page-wrapper&quot;]/div[3]/div/div/div/div/div[1]/div[1]/div/div[1]/div[3]/div/input</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
